#!/usr/bin/env bash

WITH_BEAR=$1

wmake $WITH_BEAR src/extendedBoundaryConditions  
wmake $WITH_BEAR src/leiaSurfaceInterpolation  
wmake $WITH_BEAR src/levelSetImplicitSurfaces  
wmake $WITH_BEAR src/leiaLevelSet  

wmake $WITH_BEAR all applications


