#!/usr/bin/env bash

g++ --version | head -n 1

WITH_BEAR=""
if bear --version; then
	WITH_BEAR="-with-bear"
fi

wmake $WITH_BEAR $1 src/levelSetImplicitSurfaces 
wmake $WITH_BEAR $1 src/functionObjects
wmake $WITH_BEAR $1 src/leiaLevelSet
wmake $WITH_BEAR $1 src/finiteVolume

wmake $WITH_BEAR $1 all applications


