#!/usr/bin/env bash

PATTERN=$1
LOG=$2

if [ -z "$LOG" ]; 
then 
    LOG="log"
fi

for dir in "$PATTERN"*; 
do 
    cd $dir; 
    PID_LINE=$(cat $LOG | grep PID | tail -n 1)
    PID=${PID_LINE##*:}
    echo Stopping process PID $PID
    kill -s 15 $PID
    cd .. 
done 

